apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pgdata-claim
  namespace: parent-template
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi