apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-db
  namespace: parent-template
spec:
  serviceName: keycloak-db-service
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
    spec:
      containers:
        - name: keycloak-db
          image: "localhost:5000/parent-template/keycloak-db"
          imagePullPolicy: Never
          env:
            - name: POSTGRES_USER
              value: "keycloak-admin"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "keycloak"
          volumeMounts:
            - name: keycloak-db-pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: keycloak-db-pgdata
          persistentVolumeClaim:
            claimName: keycloak-db-pgdata-claim