apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: parent-template
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 10006
      targetPort: 8080
  type: LoadBalancer