apiVersion: v1
kind: Service
metadata:
  name: rest-service
  namespace: parent-template
spec:
  selector:
    app: rest
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 8080
  type: LoadBalancer