apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: parent-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: frontend
          image: "ghcr.io/gagostin/parent-template/frontend"
          imagePullPolicy: Always
          ports:
            - containerPort: 4200