apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: parent-template
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 10004
      targetPort: 80
  type: LoadBalancer