apiVersion: v1
kind: ConfigMap
metadata:
  namespace: parent-template
  name: parent.template.keys
data:
  KEYCLOAK_DB_USER: keycloak-admin
  KEYCLOAK_DB_PASSWORD: password
  KEYCLOAK_DB_NAME: keycloak
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: admin
  KEYCLOAK_LOGLEVEL: DEBUG
  KEYCLOAK_DB_VENDOR: POSTGRES
  KEYCLOAK_DB_ADDR: keycloak-db
  KEYCLOAK_DB_DATABASE: keycloak
  KEYCLOAK_FRONTEND_URL: http://localhost:10006/auth