DROP TABLE IF EXISTS test;

CREATE TABLE IF NOT EXISTS test (
    test_id SERIAL NOT NULL,
    test_key VARCHAR(50) UNIQUE NOT NULL,
    test_value VARCHAR(50) UNIQUE NOT NULL,
    PRIMARY KEY (test_id)
);